# Generated by Django 5.1.2 on 2024-11-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view content'), ('can_create', 'Can create content'), ('can_edit', 'Can edit content'), ('can_delete', 'Can delete content')]},
        ),
    ]
