# Generated by Django 5.1.3 on 2024-12-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediauser',
            old_name='followers',
            new_name='following',
        ),
    ]
